# deploy the spark service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
  labels:
    app: spark
  namespace: project
spec:
  selector:
    matchLabels:
      app: spark
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
        - image: lichyyyyyy/14848-spark:1.0
          imagePullPolicy: IfNotPresent
          name: spark
          ports:
            # the port to be exposed
            - containerPort: 8080
              name: ui-port
            # the port for internal connection
            - containerPort: 7077
              name: spark-port
          env:
            - name: SPARK_MODE
              value: master
            - name: SPARK_SSL_ENABLED
              value: "no"
        - image: lichyyyyyy/14848-spark:1.0
          imagePullPolicy: IfNotPresent
          name: spark-worker-1
          env:
            - name: SPARK_MODE
              value: worker
            - name: SPARK_MASTER_URL
              value: "spark://spark:7077"
            - name: SPARK_WORKER_CORES
              value: "1"
        - image: lichyyyyyy/14848-spark:1.0
          imagePullPolicy: IfNotPresent
          name: spark-worker-2
          env:
            - name: SPARK_MODE
              value: worker
            - name: SPARK_MASTER_URL
              value: "spark://spark:7077"
            - name: SPARK_WORKER_CORES
              value: "1"
---
# configure the internal networking between workers and the master
apiVersion: v1
kind: Service
metadata:
  name: spark
  namespace: project
spec:
  ports:
  - port: 7077
    targetPort: 7077
  selector:
    app: spark
