apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
    app: controller
  namespace: project
spec:
  selector:
    matchLabels:
      app: controller
    
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - image: lichyyyyyy/14848-controller:1.0
          imagePullPolicy: IfNotPresent
          name: controller
          ports:
            - containerPort: 5000
          env:
            - name: hadoop_endpoint
              value: http://hadoop-service.project.svc.cluster.local:9870
            - name: spark_endpoint
              value: http://spark-service.project.svc.cluster.local:8080
            - name: sonar_endpoint
              value: http://sonar-service.project.svc.cluster.local:9000
            - name: jupyter_endpoint
              value: http://jupyter-service.project.svc.cluster.local:8888
