apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
  labels:
    app: spark
  namespace: project
spec:
  selector:
    matchLabels:
      app: spark
    
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
        - image: lichyyyyyy/14848-spark:1.0
          imagePullPolicy: IfNotPresent
          name: spark
          ports:
            - containerPort: 8080
