apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver
  labels:
    app: driver
  namespace: project
spec:
  selector:
    matchLabels:
      app: driver
    
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: driver
    spec:
      containers:
        - image: lichyyyyyy/14848-controller:1.1
          imagePullPolicy: IfNotPresent
          name: driver
          ports:
            - containerPort: 5000
          env:
            - name: hadoop_endpoint
              value: http://hadoop-lb.project.svc.cluster.local:9870
            - name: spark_endpoint
              value: http://spark-lb.project.svc.cluster.local:8080
            - name: sonar_endpoint
              value: http://sonar-lb.project.svc.cluster.local:9000
            - name: jupyter_endpoint
              value: http://jupyter-lb.project.svc.cluster.local:8888
