# expose port 80 for frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  loadBalancerIP: 35.192.106.235
  selector:
    app: frontend
---
# expose port 9870 for hadoop
apiVersion: v1
kind: Service
metadata:
  name: hadoop-lb
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 9870
    targetPort: 9870
  loadBalancerIP: 35.192.106.235
  selector:
    app: hadoop-namenode
---
# expose port 9000 for sonar
apiVersion: v1
kind: Service
metadata:
  name: sonar-lb
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
  loadBalancerIP: 35.192.106.235
  selector:
    app: sonar
---
# expose port 8080 for spark
apiVersion: v1
kind: Service
metadata:
  name: spark-lb
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  loadBalancerIP: 35.192.106.235
  selector:
    app: spark
---
# expose port 8888 for jupyter
apiVersion: v1
kind: Service
metadata:
  name: jupyter-lb
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
  loadBalancerIP: 35.192.106.235
  selector:
    app: jupyter