apiVersion: v1
kind: Service
metadata:
  name: driver-lb
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: driver
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-lb
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 9870
    targetPort: 9870
  selector:
    app: hadoop-namenode
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-lb
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: sonar
---
apiVersion: v1
kind: Service
metadata:
  name: spark-lb
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: spark
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-lb
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: jupyter