apiVersion: v1
kind: Service
metadata:
  name: controller-lb
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: controller
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-lb
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: sonar